"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

import builtins
import collections.abc
import google.protobuf.descriptor
import google.protobuf.internal.containers
import google.protobuf.message
import typing

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

@typing.final
class Ticket(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    TICKET_DATA_FIELD_NUMBER: builtins.int
    SIGNING_KEY_FIELD_NUMBER: builtins.int
    SIGNATURE_FIELD_NUMBER: builtins.int
    signature: builtins.bytes
    """ASN.1"""
    @property
    def ticket_data(self) -> global___TicketData: ...
    @property
    def signing_key(self) -> global___SigningKey: ...
    def __init__(
        self,
        *,
        ticket_data: global___TicketData | None = ...,
        signing_key: global___SigningKey | None = ...,
        signature: builtins.bytes = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["signing_key", b"signing_key", "ticket_data", b"ticket_data"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["signature", b"signature", "signing_key", b"signing_key", "ticket_data", b"ticket_data"]) -> None: ...

global___Ticket = Ticket

@typing.final
class TicketData(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    TICKET_ID_FIELD_NUMBER: builtins.int
    TRIP_DATA_FIELD_NUMBER: builtins.int
    TRAVELER_FIELD_NUMBER: builtins.int
    TICKET_ISSUE_FIELD_NUMBER: builtins.int
    PAYMENT_FIELD_NUMBER: builtins.int
    TRAIN_DATA_FIELD_NUMBER: builtins.int
    TRAIN_DATA_COUNT_FIELD_NUMBER: builtins.int
    TARIFFS_FIELD_NUMBER: builtins.int
    ticket_id: builtins.int
    train_data_count: builtins.int
    @property
    def trip_data(self) -> global___TripData: ...
    @property
    def traveler(self) -> global___TravelerData: ...
    @property
    def ticket_issue(self) -> global___TicketIssue: ...
    @property
    def payment(self) -> global___PaymentData: ...
    @property
    def train_data(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___TrainData]: ...
    @property
    def tariffs(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___Tariff]: ...
    def __init__(
        self,
        *,
        ticket_id: builtins.int = ...,
        trip_data: global___TripData | None = ...,
        traveler: global___TravelerData | None = ...,
        ticket_issue: global___TicketIssue | None = ...,
        payment: global___PaymentData | None = ...,
        train_data: collections.abc.Iterable[global___TrainData] | None = ...,
        train_data_count: builtins.int = ...,
        tariffs: collections.abc.Iterable[global___Tariff] | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["payment", b"payment", "ticket_issue", b"ticket_issue", "traveler", b"traveler", "trip_data", b"trip_data"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["payment", b"payment", "tariffs", b"tariffs", "ticket_id", b"ticket_id", "ticket_issue", b"ticket_issue", "train_data", b"train_data", "train_data_count", b"train_data_count", "traveler", b"traveler", "trip_data", b"trip_data"]) -> None: ...

global___TicketData = TicketData

@typing.final
class TripData(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    TICKET_TYPE_FIELD_NUMBER: builtins.int
    DEPARTURE_STATION_FIELD_NUMBER: builtins.int
    ARRIVAL_STATION_FIELD_NUMBER: builtins.int
    TRAVEL_CLASS_FIELD_NUMBER: builtins.int
    ROUTE_FIELD_NUMBER: builtins.int
    VALID_FROM_FIELD_NUMBER: builtins.int
    VALID_UNTIL_FIELD_NUMBER: builtins.int
    ARTICLE_NUMBER_FIELD_NUMBER: builtins.int
    ZONE_INFO_FIELD_NUMBER: builtins.int
    TARIFF_FIELD_NUMBER: builtins.int
    departure_station: builtins.str
    arrival_station: builtins.str
    travel_class: builtins.int
    article_number: builtins.int
    tariff: builtins.str
    @property
    def ticket_type(self) -> global___TicketType: ...
    @property
    def route(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.str]: ...
    @property
    def valid_from(self) -> global___Time: ...
    @property
    def valid_until(self) -> global___Time: ...
    @property
    def zone_info(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___ZoneInformation]: ...
    def __init__(
        self,
        *,
        ticket_type: global___TicketType | None = ...,
        departure_station: builtins.str = ...,
        arrival_station: builtins.str = ...,
        travel_class: builtins.int = ...,
        route: collections.abc.Iterable[builtins.str] | None = ...,
        valid_from: global___Time | None = ...,
        valid_until: global___Time | None = ...,
        article_number: builtins.int = ...,
        zone_info: collections.abc.Iterable[global___ZoneInformation] | None = ...,
        tariff: builtins.str = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["ticket_type", b"ticket_type", "valid_from", b"valid_from", "valid_until", b"valid_until"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["arrival_station", b"arrival_station", "article_number", b"article_number", "departure_station", b"departure_station", "route", b"route", "tariff", b"tariff", "ticket_type", b"ticket_type", "travel_class", b"travel_class", "valid_from", b"valid_from", "valid_until", b"valid_until", "zone_info", b"zone_info"]) -> None: ...

global___TripData = TripData

@typing.final
class TicketType(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    ID_FIELD_NUMBER: builtins.int
    NAME_FIELD_NUMBER: builtins.int
    id: builtins.int
    name: builtins.str
    def __init__(
        self,
        *,
        id: builtins.int = ...,
        name: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["id", b"id", "name", b"name"]) -> None: ...

global___TicketType = TicketType

@typing.final
class ZoneInformation(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    ZONE_ID_FIELD_NUMBER: builtins.int
    ZONE_ORG_FIELD_NUMBER: builtins.int
    zone_id: builtins.int
    zone_org: builtins.int
    def __init__(
        self,
        *,
        zone_id: builtins.int = ...,
        zone_org: builtins.int = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["zone_id", b"zone_id", "zone_org", b"zone_org"]) -> None: ...

global___ZoneInformation = ZoneInformation

@typing.final
class TravelerData(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    SBB_ID_FIELD_NUMBER: builtins.int
    SWISSPASS_ID_FIELD_NUMBER: builtins.int
    SURNAME_FIELD_NUMBER: builtins.int
    FORENAME_FIELD_NUMBER: builtins.int
    BIRTHDAY_FIELD_NUMBER: builtins.int
    TARIFF_FIELD_NUMBER: builtins.int
    sbb_id: builtins.str
    swisspass_id: builtins.str
    surname: builtins.str
    forename: builtins.str
    tariff: builtins.str
    @property
    def birthday(self) -> global___Time: ...
    def __init__(
        self,
        *,
        sbb_id: builtins.str = ...,
        swisspass_id: builtins.str = ...,
        surname: builtins.str = ...,
        forename: builtins.str = ...,
        birthday: global___Time | None = ...,
        tariff: builtins.str = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["birthday", b"birthday"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["birthday", b"birthday", "forename", b"forename", "sbb_id", b"sbb_id", "surname", b"surname", "swisspass_id", b"swisspass_id", "tariff", b"tariff"]) -> None: ...

global___TravelerData = TravelerData

@typing.final
class TicketIssue(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    ISSUE_TIME_FIELD_NUMBER: builtins.int
    ISSUING_ORG_FIELD_NUMBER: builtins.int
    issuing_org: builtins.int
    @property
    def issue_time(self) -> global___Time: ...
    def __init__(
        self,
        *,
        issue_time: global___Time | None = ...,
        issuing_org: builtins.int = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["issue_time", b"issue_time"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["issue_time", b"issue_time", "issuing_org", b"issuing_org"]) -> None: ...

global___TicketIssue = TicketIssue

@typing.final
class TrainData(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    TRAIN_ID_FIELD_NUMBER: builtins.int
    COACH_FIELD_NUMBER: builtins.int
    SEAT_FIELD_NUMBER: builtins.int
    train_id: builtins.str
    coach: builtins.str
    seat: builtins.str
    def __init__(
        self,
        *,
        train_id: builtins.str = ...,
        coach: builtins.str = ...,
        seat: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["coach", b"coach", "seat", b"seat", "train_id", b"train_id"]) -> None: ...

global___TrainData = TrainData

@typing.final
class PaymentData(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    PAYMENT_METHOD_FIELD_NUMBER: builtins.int
    CURRENCY_FIELD_NUMBER: builtins.int
    PRICE_FIELD_NUMBER: builtins.int
    payment_method: builtins.str
    currency: builtins.str
    price: builtins.str
    def __init__(
        self,
        *,
        payment_method: builtins.str = ...,
        currency: builtins.str = ...,
        price: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["currency", b"currency", "payment_method", b"payment_method", "price", b"price"]) -> None: ...

global___PaymentData = PaymentData

@typing.final
class Tariff(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    NAME_FIELD_NUMBER: builtins.int
    PASSENGER_COUNT_FIELD_NUMBER: builtins.int
    name: builtins.str
    passenger_count: builtins.int
    def __init__(
        self,
        *,
        name: builtins.str = ...,
        passenger_count: builtins.int = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["name", b"name", "passenger_count", b"passenger_count"]) -> None: ...

global___Tariff = Tariff

@typing.final
class SigningKey(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    RICS_FIELD_NUMBER: builtins.int
    KEY_ID_FIELD_NUMBER: builtins.int
    rics: builtins.str
    key_id: builtins.str
    def __init__(
        self,
        *,
        rics: builtins.str = ...,
        key_id: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["key_id", b"key_id", "rics", b"rics"]) -> None: ...

global___SigningKey = SigningKey

@typing.final
class Time(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    MSECS_FIELD_NUMBER: builtins.int
    msecs: builtins.int
    def __init__(
        self,
        *,
        msecs: builtins.int = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["msecs", b"msecs"]) -> None: ...

global___Time = Time
