"""
Django settings for vdv_pkpass project.

Generated by 'django-admin startproject' using Django 4.2.10.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

import json

import cryptography.x509
import cryptography.hazmat.primitives.serialization
import google.oauth2.service_account
import google.auth.crypt
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "django-insecure-%d$d(=tg6tengouqane%hj*_fr8r-w^g7vf@z_cmxmr!v9&)#a"

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ["localhost", "vdv-pkpass.eu.ngrok.io", "127.0.0.1"]

# SECURITY WARNING: We know. They have lawyers.
BARKODER_LICENSE = "0MHXR8cuvoJT62F-vUCcqMQR74K0988ixUjSf_DnucZlrv_DJTneGfAh1avJBr72P0VecEQGK5JHDH0FmfI_Lp8PdEdFGLDlQzT_axGBusQQWRt4-vYYaAyxrCvqtGWZIVN6jhCiyvQ7fndQ7oDAwhdpufGp1KH2tYFeNfif84DE8anuMEXfTOGUjN3jfEu1"

# Application definition

INSTALLED_APPS = [
    "daphne",
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "crispy_forms",
    "crispy_forms_gds",
    "magiclink",
    "main",
    "channels",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

AUTHENTICATION_BACKENDS = [
    'magiclink.backends.MagicLinkBackend',
    'django.contrib.auth.backends.ModelBackend',
]

ROOT_URLCONF = "vdv_pkpass.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
                "main.context_processors.git_hash_context",
            ],
        },
    },
]

WSGI_APPLICATION = "vdv_pkpass.wsgi.application"
ASGI_APPLICATION = "vdv_pkpass.asgi.application"

# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR / "db.sqlite3",
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = "static/"
STATIC_ROOT = BASE_DIR / "static"
MEDIA_URL = "media/"
MEDIA_ROOT = BASE_DIR / "media"


# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

EXTERNAL_URL_BASE = "https://vdv-pkpass.eu.ngrok.io"

CRISPY_ALLOWED_TEMPLATE_PACKS = ["gds"]
CRISPY_TEMPLATE_PACK = "gds"

PKPASS_CERTIFICATE_LOCATION = BASE_DIR / "priv" / "pass.crt"
PKPASS_KEY_LOCATION = BASE_DIR / "priv" / "pass.key"

MAPKIT_KEY_LOCATION = BASE_DIR / "priv" / "mapkit.p8"
MAPKIT_KEY_ID = "MY5M7WRR28"

try:
    with open(BASE_DIR / "priv" / "nr.json") as f:
        d = json.load(f)
        NR_USERNAME = d["username"]
        NR_PASSWORD = d["password"]
except FileNotFoundError:
    NR_USERNAME = None
    NR_PASSWORD = None

try:
    with open(BASE_DIR / "priv" / "db.json") as f:
        d = json.load(f)
        DB_CLIENT_ID = d["client_id"]
        DB_API_KEY = d["api_key"]
except FileNotFoundError:
    DB_CLIENT_ID = None
    DB_API_KEY = None

try:
    with open(BASE_DIR / "priv" / "sncb.json") as f:
        d = json.load(f)
        SNCB_API_KEY = d["api_key"]
except FileNotFoundError:
    SNCB_API_KEY = None

try:
    with open(BASE_DIR / "priv" / "wwdrg4.crt", "rb") as f:
        WWDR_CERTIFICATE = cryptography.x509.load_der_x509_certificate(f.read())
except FileNotFoundError:
    WWDR_CERTIFICATE = None

try:
    with open(PKPASS_CERTIFICATE_LOCATION, "rb") as f:
        PKPASS_CERTIFICATE = cryptography.x509.load_pem_x509_certificate(f.read())
except FileNotFoundError:
    PKPASS_CERTIFICATE = None

try:
    with open(PKPASS_KEY_LOCATION, "rb") as f:
        PKPASS_KEY = cryptography.hazmat.primitives.serialization.load_pem_private_key(f.read(), None)
except FileNotFoundError:
    PKPASS_KEY = None

try:
    with open(MAPKIT_KEY_LOCATION, "rb") as f:
        MAPKIT_KEY = cryptography.hazmat.primitives.serialization.load_pem_private_key(f.read(), None)
except FileNotFoundError:
    MAPKIT_KEY = None

try:
    GOOGLE_CREDS = google.oauth2.service_account.Credentials.from_service_account_file(
        str((BASE_DIR / "priv" / "google-creds.json").absolute()),
        scopes=['https://www.googleapis.com/auth/wallet_object.issuer']
    )
    GOOGLE_SIGNER = google.auth.crypt.RSASigner.from_service_account_file(
        str((BASE_DIR / "priv" / "google-creds.json").absolute())
    )
except FileNotFoundError:
    GOOGLE_CREDS = None
    GOOGLE_SIGNER = None

GIT_HASH = None

PKPASS_CONF = {
    "organization_name": "VDV PKPass",
    "pass_type": "pass.ch.magicalcodewit.vdv.ticket",
    "team_id": "MQ9TN9772U"
}
GWALLET_CONF = {
    "issuer_id": "3388000000009246234",
    "railcard_pass_class": "pass.ch.magicalcodewit.vdv.railcard",
    "train_ticket_pass_class": "pass.ch.magicalcodewit.vdv.ticket",
    "train_pass_class": "pass.ch.magicalcodewit.vdv.train",
    "bahncard_pass_class": "pass.ch.magicalcodewit.vdv.bahncard",
}

AZTEC_JAR_PATH = BASE_DIR / "aztec" / "target" / "aztec-1.0.jar"

STORAGES = {
    "default": {
        "BACKEND": "django.core.files.storage.FileSystemStorage",
    },
    "staticfiles": {
        "BACKEND": "django.contrib.staticfiles.storage.StaticFilesStorage",
    },
    "vdv-certs": {
        "BACKEND": "django.core.files.storage.FileSystemStorage",
        "OPTIONS": {
            "location": BASE_DIR / "vdv-certs",
        }
    },
    "uic-data": {
        "BACKEND": "django.core.files.storage.FileSystemStorage",
        "OPTIONS": {
            "location": BASE_DIR / "uic-data",
        }
    },
    "rsp-data": {
        "BACKEND": "django.core.files.storage.FileSystemStorage",
        "OPTIONS": {
            "location": BASE_DIR / "rsp-data",
        }
    },
    "iata-data": {
        "BACKEND": "django.core.files.storage.FileSystemStorage",
        "OPTIONS": {
            "location": BASE_DIR / "iata-data",
        }
    },
}

LOGIN_URL = "magiclink:login"
LOGIN_REDIRECT_URL = "account"
LOGOUT_REDIRECT_URL = "index"

MAGICLINK_LOGIN_TEMPLATE_NAME = "registration/magic_login.html"
MAGICLINK_LOGIN_SENT_TEMPLATE_NAME = "registration/magic_sent.html"
MAGICLINK_LOGIN_FAILED_TEMPLATE_NAME = "registration/magic_failed.html"
MAGICLINK_SIGNUP_TEMPLATE_NAME = "registration/magic_signup.html"
MAGICLINK_EMAIL_SUBJECT = "VDV PKPass Login"
MAGICLINK_EMAIL_TEMPLATE_NAME_TEXT = "registration/magic_email.txt"
MAGICLINK_EMAIL_TEMPLATE_NAME_HTML = "registration/magic_email.html"
MAGICLINK_REQUIRE_SIGNUP = True
MAGICLINK_IGNORE_EMAIL_CASE = True
MAGICLINK_EMAIL_AS_USERNAME = True
MAGICLINK_ALLOW_SUPERUSER_LOGIN = False
MAGICLINK_ALLOW_STAFF_LOGIN = False
MAGICLINK_IGNORE_IS_ACTIVE_FLAG = False
MAGICLINK_REQUIRE_SAME_BROWSER = False
MAGICLINK_REQUIRE_SAME_IP = False
MAGICLINK_ANONYMIZE_IP = False
MAGICLINK_TOKEN_USES = 1
MAGICLINK_AUTH_TIMEOUT = 900

EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'
DEFAULT_FROM_EMAIL = "VDV PKPass <noreply@magicalcodewit.ch>"

CSRF_TRUSTED_ORIGINS = ["http://localhost", "https://vdv-pkpass.eu.ngrok.io"]

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'filters': {
        'require_debug_false': {
            '()': 'django.utils.log.RequireDebugFalse',
        },
        'require_debug_true': {
            '()': 'django.utils.log.RequireDebugTrue',
        },
    },
    'formatters': {
        'django.server': {
            '()': 'django.utils.log.ServerFormatter',
            'format': '[%(server_time)s] %(message)s',
        }
    },
    'handlers': {
        'console': {
            'level': 'INFO',
            'filters': ['require_debug_true'],
            'class': 'logging.StreamHandler',
        },
        'console_debug_false': {
            'level': 'ERROR',
            'filters': ['require_debug_false'],
            'class': 'logging.StreamHandler',
        },
        'django.server': {
            'level': 'INFO',
            'class': 'logging.StreamHandler',
            'formatter': 'django.server',
        },
    },
    'loggers': {
        'django': {
            'handlers': ['console', 'console_debug_false'],
            'level': 'INFO',
        },
        'django.server': {
            'handlers': ['django.server'],
            'level': 'INFO',
            'propagate': False,
        }
    }
}
