# Generated by Django 5.0.9 on 2025-01-26 13:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0042_hzppticketinstance'),
    ]

    operations = [
        migrations.CreateModel(
            name='SwissPassTicketInstance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('barcode_hash', models.CharField(max_length=64, unique=True)),
                ('barcode_data', models.BinaryField()),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='swisspass_instances', to='main.ticket')),
            ],
            options={
                'verbose_name': 'SwissPass ticket',
            },
        ),
    ]
