# Generated by Django 5.0.9 on 2025-01-28 11:28
import uuid

import main.models
from django.db import migrations, models

def set_defaults(apps, schema_editor):
    for account in apps.get_model('main', 'Account').objects.all().iterator():
        account.calendar_token = main.models.make_pass_token()
        account.save()


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0044_uic_signed_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='calendar_token',
            field=models.CharField(null=True, max_length=255, verbose_name='iCal token'),
        ),
        migrations.RunPython(set_defaults, lambda a, s: None),
        migrations.AlterField(
            model_name='account',
            name='calendar_token',
            field=models.CharField(null=False, max_length=255, verbose_name='iCal token'),
        ),
    ]
