# Generated by Django 5.0.9 on 2025-02-16 12:01

import django.db.models.deletion
import main.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0045_account_calendar_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='calendar_token',
            field=models.CharField(default=main.models.make_pass_token, max_length=255, verbose_name='iCal token'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='ticket_type',
            field=models.CharField(choices=[('deutschlandticket', 'Deutschlandticket'), ('klimaticket', 'Klimaticket'), ('bahncard', 'Bahncard'), ('fahrkarte', 'Fahrkarte'), ('bordkarte', 'Bordkarte'), ('reservierung', 'Reservierung'), ('interrail', 'Interrail'), ('railcard', 'Railcard'), ('keycard', 'Keycard'), ('unknown', 'Unknown')], default='unknown', max_length=255, verbose_name='Ticket type'),
        ),
        migrations.CreateModel(
            name='IATATicketInstance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('barcode_hash', models.CharField(max_length=64, unique=True)),
                ('barcode_data', models.BinaryField()),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='iata_instances', to='main.ticket')),
            ],
            options={
                'verbose_name': 'IATA ticket',
            },
        ),
    ]
