# Generated by Django 5.0.9 on 2025-02-27 19:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0047_ticket_created'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccessLogEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('upload', 'Upload ticket barcode'), ('download-pkpass', 'Download PKPass')], max_length=255)),
                ('remote_ip', models.GenericIPAddressField()),
                ('headers', models.JSONField(default=dict)),
                ('account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='access_logs', to='main.account')),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_logs', to='main.ticket')),
            ],
        ),
    ]
