# Generated by Django 5.0.9 on 2025-02-27 19:18

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0048_accesslogentry'),
    ]

    operations = [
        migrations.AddField(
            model_name='accesslogentry',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
