# Generated by Django 5.0.9 on 2025-03-23 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0050_bahnbonusinstance'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='bahnbonus_refresh_token',
            field=models.TextField(blank=True, null=True, verbose_name='BahnBonus refresh token'),
        ),
        migrations.AddField(
            model_name='account',
            name='bahnbonus_refresh_token_expires_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='BahnBonus refresh token expiration'),
        ),
        migrations.AddField(
            model_name='account',
            name='bahnbonus_token',
            field=models.TextField(blank=True, null=True, verbose_name='BahnBonus bearer token'),
        ),
        migrations.AddField(
            model_name='account',
            name='bahnbonus_token_expires_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='BahnBonus bearer token expiration'),
        ),
        migrations.AlterField(
            model_name='account',
            name='db_token',
            field=models.TextField(blank=True, null=True, verbose_name='Deutsche Bahn bearer token'),
        ),
        migrations.AlterField(
            model_name='account',
            name='db_token_expires_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Deutsche Bahn bearer token expiration'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='ticket_type',
            field=models.CharField(choices=[('deutschlandticket', 'Deutschlandticket'), ('klimaticket', 'Klimaticket'), ('bahncard', 'Bahncard'), ('fahrkarte', 'Fahrkarte'), ('bordkarte', 'Bordkarte'), ('reservierung', 'Reservierung'), ('interrail', 'Interrail'), ('railcard', 'Railcard'), ('keycard', 'Keycard'), ('bahnbonus', 'BahnBonus'), ('unknown', 'Unknown')], default='unknown', max_length=255, verbose_name='Ticket type'),
        ),
    ]
