# Generated by Django 5.0.9 on 2025-03-29 22:30
import main.models
from django.db import migrations, models

def set_defaults(apps, schema_editor):
    for account in apps.get_model('main', 'Account').objects.all():
        account.nfc_link_token = main.models.make_pass_token()
        account.save()


class Migration(migrations.Migration):
    dependencies = [
        ('main', '0054_alter_vdvsmartcard_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='nfc_link_token',
            field=models.CharField(null=True, max_length=255, verbose_name='NFC link token'),
        ),
        migrations.RunPython(set_defaults, lambda a, s: None),
        migrations.AlterField(
            model_name='account',
            name='nfc_link_token',
            field=models.CharField(null=False, max_length=255, verbose_name='NFC link token'),
        ),
    ]
