# Generated by Django 5.0.9 on 2025-03-29 23:35

import main.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0055_account_nfc_link_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='vdvsmartcard',
            name='application_data',
            field=models.BinaryField(default=b''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vdvsmartcard',
            name='application_info_text',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='vdvsmartcard',
            name='customer_info_text',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='vdvsmartcard',
            name='key_register',
            field=models.BinaryField(default=b''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='account',
            name='nfc_link_token',
            field=models.CharField(default=main.models.make_pass_token, max_length=255, verbose_name='NFC link token'),
        ),
    ]
