# Generated by Django 5.0.9 on 2025-03-30 00:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0056_vdvsmartcard_application_data_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='VDVSmartcardLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence_number', models.IntegerField()),
                ('log_entry', models.BinaryField()),
                ('smartcard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='main.vdvsmartcard')),
            ],
            options={
                'unique_together': {('smartcard', 'sequence_number')},
            },
        ),
    ]
