# Generated by Django 5.0.9 on 2025-04-10 14:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0058_alter_vdvsmartcardlog_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='avv_refresh_token',
            field=models.TextField(blank=True, null=True, verbose_name='AVV Refresh token'),
        ),
        migrations.AddField(
            model_name='account',
            name='avv_refresh_token_expires_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='AVV Rrefresh token expiration'),
        ),
        migrations.AddField(
            model_name='account',
            name='avv_token',
            field=models.TextField(blank=True, null=True, verbose_name='AVV Bearer token'),
        ),
        migrations.AddField(
            model_name='account',
            name='avv_token_expires_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='AVV Bearer token expiration'),
        ),
        migrations.AlterField(
            model_name='bahnbonusinstance',
            name='barcode_hash',
            field=models.CharField(db_index=True, max_length=64, unique=True),
        ),
        migrations.AlterField(
            model_name='elbticketinstance',
            name='barcode_hash',
            field=models.CharField(db_index=True, max_length=64, unique=True),
        ),
        migrations.AlterField(
            model_name='hzppticketinstance',
            name='barcode_hash',
            field=models.CharField(db_index=True, max_length=64, unique=True),
        ),
        migrations.AlterField(
            model_name='iataticketinstance',
            name='barcode_hash',
            field=models.CharField(db_index=True, max_length=64, unique=True),
        ),
        migrations.AlterField(
            model_name='rspticketinstance',
            name='issuer_id',
            field=models.CharField(db_index=True, max_length=2, verbose_name='Issuer ID'),
        ),
        migrations.AlterField(
            model_name='rspticketinstance',
            name='reference',
            field=models.CharField(db_index=True, max_length=20, verbose_name='Ticket reference'),
        ),
        migrations.AlterField(
            model_name='sncfticketinstance',
            name='barcode_hash',
            field=models.CharField(db_index=True, max_length=64, unique=True),
        ),
        migrations.AlterField(
            model_name='ssb1ticketinstance',
            name='barcode_hash',
            field=models.CharField(db_index=True, max_length=64, unique=True),
        ),
        migrations.AlterField(
            model_name='ssb1ticketinstance',
            name='distributor_rics',
            field=models.PositiveIntegerField(db_index=True, validators=[django.core.validators.MaxValueValidator(9999)], verbose_name='Distributor RICS'),
        ),
        migrations.AlterField(
            model_name='ssbticketinstance',
            name='barcode_hash',
            field=models.CharField(db_index=True, max_length=64, unique=True),
        ),
        migrations.AlterField(
            model_name='ssbticketinstance',
            name='distributor_rics',
            field=models.PositiveIntegerField(db_index=True, validators=[django.core.validators.MaxValueValidator(9999)], verbose_name='Distributor RICS'),
        ),
        migrations.AlterField(
            model_name='swisspassticketinstance',
            name='barcode_hash',
            field=models.CharField(db_index=True, max_length=64, unique=True),
        ),
        migrations.AlterField(
            model_name='uicticketinstance',
            name='barcode_hash',
            field=models.CharField(db_index=True, max_length=64, unique=True),
        ),
        migrations.AlterField(
            model_name='uicticketinstance',
            name='distributor_rics',
            field=models.PositiveIntegerField(db_index=True, validators=[django.core.validators.MaxValueValidator(9999)], verbose_name='Distributor RICS'),
        ),
        migrations.AlterField(
            model_name='vdvticketinstance',
            name='barcode_hash',
            field=models.CharField(db_index=True, max_length=64, unique=True),
        ),
        migrations.AlterField(
            model_name='vdvticketinstance',
            name='ticket_org_id',
            field=models.PositiveIntegerField(db_index=True, verbose_name='Organization ID'),
        ),
        migrations.AlterIndexTogether(
            name='rspticketinstance',
            index_together={('ticket_type', 'reference', 'issuer_id')},
        ),
    ]
