# Generated by Django 5.0.9 on 2025-04-10 14:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0059_account_avv_refresh_token_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='avv_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='avv_tickets', to='main.account', verbose_name='AVV Account'),
        ),
    ]
