# Generated by Django 5.0.9 on 2025-04-10 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0060_ticket_avv_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='avv_device_id',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='AVV Device ID'),
        ),
    ]
